"""initial_schema_fixed

Revision ID: 9614ea3239d0
Revises: 
Create Date: 2026-01-02 23:15:14.107769+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9614ea3239d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_framework', sa.Enum('FLASK', 'FASTAPI', 'DJANGO', 'EXPRESS', 'FASTIFY', 'NEXTJS', 'SPRING_BOOT', 'QUARKUS', 'CUSTOM', name='frameworktype'), nullable=False),
    sa.Column('target_framework', sa.Enum('FLASK', 'FASTAPI', 'DJANGO', 'EXPRESS', 'FASTIFY', 'NEXTJS', 'SPRING_BOOT', 'QUARKUS', 'CUSTOM', name='frameworktype'), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('branch', sa.String(length=255), server_default='main', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'READY', 'MIGRATING', 'COMPLETED', 'FAILED', name='projectstatus'), server_default='PENDING', nullable=False),
    sa.Column('total_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_chunks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('qdrant_collection', sa.String(length=255), nullable=True),
    sa.Column('neo4j_graph_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('code_chunks',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.Enum('FUNCTION', 'CLASS', 'METHOD', 'MODULE', 'ROUTE', 'CONFIG', 'TEST', 'DOCUMENTATION', 'OTHER', name='chunktype'), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=36), nullable=True),
    sa.Column('neo4j_node_id', sa.String(length=100), nullable=True),
    sa.Column('migration_status', sa.Enum('PENDING', 'IN_PROGRESS', 'MIGRATED', 'NEEDS_REVIEW', 'FAILED', 'SKIPPED', name='migrationstatus'), server_default='PENDING', nullable=False),
    sa.Column('migrated_content', sa.Text(), nullable=True),
    sa.Column('migration_confidence', sa.Float(), nullable=True),
    sa.Column('ast_metadata', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('dependents', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_chunk_type'), 'code_chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_code_chunks_file_path'), 'code_chunks', ['file_path'], unique=False)
    op.create_index(op.f('ix_code_chunks_migration_status'), 'code_chunks', ['migration_status'], unique=False)
    op.create_index(op.f('ix_code_chunks_name'), 'code_chunks', ['name'], unique=False)
    op.create_index(op.f('ix_code_chunks_neo4j_node_id'), 'code_chunks', ['neo4j_node_id'], unique=False)
    op.create_index(op.f('ix_code_chunks_project_id'), 'code_chunks', ['project_id'], unique=False)
    op.create_index(op.f('ix_code_chunks_qdrant_point_id'), 'code_chunks', ['qdrant_point_id'], unique=True)
    op.create_table('migration_jobs',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PLANNING', 'MIGRATING', 'TESTING', 'FIXING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), server_default='QUEUED', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('total_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('agent_state', sa.JSON(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_files', sa.JSON(), nullable=True),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_jobs_project_id'), 'migration_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_migration_jobs_status'), 'migration_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_migration_jobs_status'), table_name='migration_jobs')
    op.drop_index(op.f('ix_migration_jobs_project_id'), table_name='migration_jobs')
    op.drop_table('migration_jobs')
    op.drop_index(op.f('ix_code_chunks_qdrant_point_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_project_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_neo4j_node_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_name'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_migration_status'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_file_path'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_chunk_type'), table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
